spring:
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: 'iot-devices-group'

relay42:
  iotdataprocessing:
    config:
      spark:
        app:
          name: IOT data pipeline
        #master: spark://localhost:7077
        master: local
        checkpoint:
          dir: hdfs://0.0.0.0:8020/iot-pipeline/checkpoint
      cassandra:
        host: localhost
        port: 9042
        username: cassandra
        password: cassandra
        keep_alive: 10000
      hdfs:
        parquetLocation: hdfs://0.0.0.0:8020/iot-pipeline/iot-data-parque
      kafka:
        topic: H02
