spring:
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: 'iot-devices-group'
#### Cassandra Migration properties

cassandra:
  migration:
    keyspace-name: iot_data_store

relay42:
  iotdataprocessing:
    config:
      spark:
        app:
          name: IOT data pipeline
        #master: spark://localhost:7077
        master: local[*]
        checkpoint:
          dir: temp/iot-pipeline-data/checkpoint
#         dir: hdfs://0.0.0.0:8020/iot-pipeline/checkpoint
      cassandra:
        keyspace-name: iot_data_store
        local-datacenter: DC1
        host: 127.0.0.1
        port: 9042
        username: cassandra
        password: cassandra
        keep_alive: 10000
      hdfs:
#        parquetLocation: hdfs://0.0.0.0:8020/iot-pipeline/iot-data-parque
        parquetLocation: /Users/devender.kumar/Documents/personal-space/iot-data-pipeline/iot-data-processing-service/iot-data-parque
      kafka:
        topic: H02
